name: Build Blog

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 8.1.1
          # If specified, run `pnpm install`
          run_install: true

      - name: Build
        run: pnpm build
