name: Build Blog

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    environment: blog

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.5
          run_install: true

      - name: build
        run: pnpm build
      
      - name: tar
        run: |
          cd docs/.vitepress
          tar -zcvf ../../dist.tar.gz dist
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist.tar.gz"
          target: /data/blog-dir
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /data/blog-dir/
            mkdir temp
            tar -zxvf dist.tar.gz -C temp
            rm -rf dist/
            mv temp/dist dist/
            rm -rf temp
